POST http://localhost:3001/api/users
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpzYW5jaCIsImlkIjoiNWYzYmQzNzRjYzFhMTU0ZTM4MjcwOGM4IiwiaWF0IjoxNTk5NTk2MzAyfQ.P2Anx2-Be8zfc5CnY-hCUffvxbNHA87EBog-DujpAQU

{
  "username": "jsan",
  "name": "josh",
  "password": "animal"
}

###